
workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always


variables:
  DOCKER_REGISTRY: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/wearestancer


phpcs:
  stage: test

  image: ${DOCKER_REGISTRY}/php:7.4-xdebug3.1

  before_script:
    - php -v
    - composer --version

    - composer install
    - ./vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs/WordPress,vendor/wp-coding-standards/wpcs/WordPress-Core,vendor/wp-coding-standards/wpcs/WordPress-Docs,vendor/wp-coding-standards/wpcs/WordPress-Extra

  script:
    - ./vendor/bin/phpcs || true
    - ./vendor/bin/phpcs --report=junit --report-file=phpcs.junit.xml

  artifacts:
    reports:
      junit: phpcs.junit.xml
