
workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always


variables:
  DOCKER_REGISTRY: wearestancer
  PHP_VERSION: "7.4"


.svn-publish:
  stage: deploy

  image: ${DOCKER_REGISTRY}/wordpress:svn

  before_script:
    - svn co https://plugins.svn.wordpress.org/stancer svn
    - cd svn


Create archive:
  stage: deploy

  image: ${DOCKER_REGISTRY}/wordpress:php${PHP_VERSION}

  before_script:
    - php -v
    - composer --version
    - pnpm --version

    # Apply git filters
    - sh scripts/git-filters.sh 1

    - pnpm install

  script:
    - pnpm run build:archive
    - export ZIP_NAME="wc-${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}"
    - echo "${ZIP_NAME}"
    - mv stancer*.zip "${ZIP_NAME}.zip"

  artifacts:
    paths:
      - '*.zip'


phpcs:
  stage: test

  image: ${DOCKER_REGISTRY}/php:${PHP_VERSION}

  before_script:
    - php -v
    - composer --version

    - composer install

  script:
    - ./vendor/bin/phpcs || true
    - ./vendor/bin/phpcs --report=junit --report-file=phpcs.junit.xml

  artifacts:
    reports:
      junit: phpcs.junit.xml


Publish main changes:
  extends:
    - .svn-publish

  script:
    - export TEMP_FOLDER="$(mktemp -d)"
    - unzip -o ../*.zip -d "$TEMP_FOLDER"
    - rsync -Sa --delete "${TEMP_FOLDER}/stancer/" trunk/
    - svn add --force trunk/*
    - svn stat
    - svn ci -m "$CI_COMMIT_TITLE" --username "$SVN_USER" --password "$SVN_PASSWD"

  needs:
    - job: Create archive
      artifacts: true

  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $SVN_USER && $SVN_PASSWD && $CI_COMMIT_REF_PROTECTED


Publish version:
  extends:
    - .svn-publish

  script:
    - export VERSION="${CI_COMMIT_TAG/v/}"
    - svn cp trunk "tags/${VERSION}"
    - svn ci -m "Version ${VERSION}" --username "$SVN_USER" --password "$SVN_PASSWD"

  rules:
    - if: $SVN_USER && $SVN_PASSWD && $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED
