#! /bin/bash

set -eu -o pipefail

site_host="woocommerce.localtest.stancer.network"
site_port=10020
site_title="WooCommerce Testing"

wordpress_dir=/var/www/html
plugin_dir="${wordpress_dir}/wp-content/plugins/stancer"
devcontainer_dir="${plugin_dir}/.devcontainer"

admin_email="shop-admin@stancer.com"
admin_password="shop-admin"

user_email="shop-user@stancer.com"
user_password="shop-user"
user_firstname="John"
user_lastname="Doe"


# Adding our directory as a safe directory.
git config --global --add safe.directory "$plugin_dir"
sh "${plugin_dir}/scripts/git-filters.sh"


# Install dependencies
composer install --working-dir="${plugin_dir}"
pnpm config set store-dir "${HOME}/.cache/pnpm"
pnpm install --dir "${plugin_dir}"

# Prepare assets
pnpm run --dir "${plugin_dir}" build:assets


# Get Caddy root CA
curl http://caddy:2019/pki/ca/local/certificates -so "${devcontainer_dir}/root-ca.crt"


# Wordpress

# Prerequires
sudo chmod g+w "${wordpress_dir}/wp-config.php"
sudo mkdir --mode=775 -p "${wordpress_dir}/wp-content/upgrade"
sudo chown -R www-data:www-data "${wordpress_dir}/wp-content/upgrade"
sudo chmod g+w "${wordpress_dir}/wp-content/plugins"
sudo chmod g+w "${wordpress_dir}/wp-content/themes"

# Activate debug
wp --path="$wordpress_dir" config set WP_DEBUG true --raw
wp --path="$wordpress_dir" config set WP_DEBUG_LOG true --raw

# Run the installer (similar to the browser install)
wp --path="$wordpress_dir" core install \
  --url="${site_host}:${site_port}" \
  --title="$site_title" \
  --admin_user="$admin_email" \
  --admin_password="$admin_password" \
  --admin_email="$admin_email"

# Make HTTPS the default
wp --path="$wordpress_dir" option update siteurl "https://${site_host}:${site_port}"
wp --path="$wordpress_dir" option update home "https://${site_host}:${site_port}"


# Remove default starter modules
wp --path="$wordpress_dir" plugin uninstall --all --exclude=stancer,woocommerce,woocommerce-subscriptions,wp-mail-smtp


# Install SMTP plugin
command=$(wp --path="$wordpress_dir" plugin list --field=name --status=active | grep wp-mail-smtp || true)
if [ -z "$command" ]; then
  wp --path="$wordpress_dir" plugin install --activate wp-mail-smtp
  wp --path="$wordpress_dir" option add --format=json wp_mail_smtp_review_notice <<CONF
{
  "time": $(date +%s),
  "dismissed": false
}
CONF
fi

configuration_name="wp_mail_smtp"
wp --path="$wordpress_dir" option patch update --json "$configuration_name" smtp <<CONF
{
  "auth": false,
  "autotls": false,
  "host": "mailtrap",
  "port": 25
}
CONF
wp --path="$wordpress_dir" option patch update "$configuration_name" mail mailer smtp


# Install woocommerce
command=$(wp --path="$wordpress_dir" plugin list --field=name --status=active | grep woocommerce || true)
if [ -z "$command" ]; then
  wp --path="$wordpress_dir" plugin install --activate woocommerce
fi

# Create some example products
products=()
products+=("Brique de lait;simple;1.99;Un puissant produit laitier de test;SKU-milk-bottle")
products+=("Sandwich;simple;3.25;Un sandwich testable;SKU-sandwich")
products+=("Pack de lait;simple;12.00;Plein de calcium pour des tests solides;SKU-milk-pack")
products+=("Testing Magazine No.120;simple;24.99;Le magazine de WooCommerce;SKU-magazine")

for product in "${products[@]}" ; do
  name=$(echo "$product" | cut -d';' -f1)
  type=$(echo "$product" | cut -d';' -f2)
  price=$(echo "$product" | cut -d';' -f3)
  desc=$(echo "$product" | cut -d';' -f4)
  sku=$(echo "$product" | cut -d';' -f5)

  command=$(wp --path="$wordpress_dir" wc product list --user=1 --format=count --sku="$sku")

  if [ "$command" == 0 ]; then
    echo "Add product $name"
    wp --path="$wordpress_dir" wc product create \
      --name="$name" \
      --type="$type" \
      --regular_price="$price" \
      --description="$desc" \
      --sku="$sku" \
      --user=1
  fi
done


# Add a default user
command=$(wp --path="$wordpress_dir" wc customer list --user=1 --email="$user_email" --format=count)

if [ "$command" == 0 ]; then
  addr=$(cat <<ADDR
{
  "first_name": "$user_firstname",
  "last_name": "$user_lastname",
  "email": "$user_email",
  "phone": "+33123456789",
  "address_1": "42 $user_firstname $user_lastname street",
  "postcode": "99999",
  "city": "CITY",
  "country": "FR"
}
ADDR
)

  wp --path="$wordpress_dir" wc customer create --user=1 \
    --first_name="$user_firstname" \
    --last_name="$user_lastname" \
    --email="$user_email" \
    --username="$user_email" \
    --password="$user_password" \
    --billing="$addr" \
    --shipping="$addr"

  addr=$(cat <<ADDR
{
  "first_name": "$user_firstname",
  "last_name": "$user_lastname",
  "email": "shop-admin@stancer.com",
  "phone": "+33123456789",
  "address_1": "42 $user_firstname $user_lastname street",
  "postcode": "99999",
  "city": "CITY",
  "country": "FR"
}
ADDR
)

  wp --path="$wordpress_dir" wc customer update 1 --user=1 --billing="$addr" --shipping="$addr"
fi


# Set some defaults
wp --path="$wordpress_dir" option update woocommerce_allow_tracking "no"
wp --path="$wordpress_dir" option update woocommerce_no_sales_tax 1
wp --path="$wordpress_dir" option update woocommerce_default_country "FR"


# Running package manager updates
composer update
pnpm install
pnpm run build:assets


# Install our plugin
command=$(wp --path="$wordpress_dir" plugin list --field=name --status=active | grep stancer || true)
if [ -z "$command" ]; then
  wp --path="$wordpress_dir" plugin activate stancer
fi

# Configure it
if [ -f .devcontainer/.env ]; then
  source .devcontainer/.env

  configuration_name="woocommerce_stancer_settings"
  command=$(wp --path="$wordpress_dir" option list --search="$configuration_name" --format=count)

  if [ "$command" == 0 ]; then
    wp --path="$wordpress_dir" option add --format=json "$configuration_name" <<CONF
{
  "api_live_public_key": "",
  "api_live_secret_key": "",
  "api_test_public_key": "",
  "api_test_secret_key": "",
  "enabled": "yes",
  "host": "",
  "page_type": "pip",
  "payment_description": "Your order SHOP_NAME",
  "payment_option_description": "",
  "payment_option_logo": "all-schemes-stancer",
  "payment_option_text": "Pay by card",
  "test_mode": "yes"
}
CONF
  fi

  if [ -n "${API_PUBLIC_KEY:-}" ]; then
    wp --path="$wordpress_dir" option patch update "$configuration_name" api_test_public_key "$API_PUBLIC_KEY"
  fi

  if [ -n "${API_SECRET_KEY:-}" ]; then
    wp --path="$wordpress_dir" option patch update "$configuration_name" api_test_secret_key "$API_SECRET_KEY"
  fi

  if [ -n "${API_HOST:-}" ]; then
    wp --path="$wordpress_dir" option patch update "$configuration_name" host "$API_HOST"
  fi


  if [ -n "${WP_THEME:-}" ]; then
    command=$(wp --path="$wordpress_dir" theme list --field=name | grep "$WP_THEME" || true)

    if [ -z "$command" ]; then
      wp --path="$wordpress_dir" theme install --activate "$WP_THEME"
    else
      wp --path="$wordpress_dir" theme activate "$WP_THEME"
    fi
  fi
fi


# Local configuration
if [ -f "${wordpress_dir}/wp-content/plugins/stancer/.devcontainer/post-attach.local.sh" ]; then
  /bin/bash "${wordpress_dir}/wp-content/plugins/stancer/.devcontainer/post-attach.local.sh"
fi



# Output
underline=$(tput smul)
nounderline=$(tput rmul)
bold=$(tput bold)
normal=$(tput sgr0)
red="\033[38;5;9m"

echo ""
echo "${underline}${bold}Default settings${normal}${nounderline}"
echo ""
echo "Website accessible at:      https://${site_host}:${site_port}"
echo "Admin panel accessible at:  https://${site_host}:${site_port}/wp-admin"
echo ""
echo "Admin login:                $admin_email"
echo "Admin password:             $admin_password"
echo ""
echo "Test user login:            $user_email"
echo "Test user password:         $user_password"

if [ -z "${API_PUBLIC_KEY:-}" ] || [ -z "${API_SECRET_KEY:-}" ]; then
  echo ""
  echo -e "${bold}${red}Your Stancer API keys are not properly setup do not forget to set them.${normal}"
  echo ""
fi
