services:
  caddy:
    image: caddy:alpine

    depends_on:
      wordpress:
        condition: service_started

    networks:
      - app
      - mail

    ports:
      - 127.0.0.1:10020:10020
      - 127.0.0.1:10020:10020/udp
      - 127.0.0.1:10021:10021

    restart: unless-stopped

    volumes:
      - caddy-config:/config/caddy
      - caddy-data:/data/caddy
      - root-path:/var/www/html
      - ./fs/etc/caddy:/etc/caddy
      - ..:/var/www/html/wp-content/plugins/stancer:cached


  database:
    image: mariadb:latest

    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_ROOT_PASSWORD: root

    healthcheck:
      interval: 1s
      retries: 3
      start_period: 10s
      test: mariadb-admin ping -u root -proot
      timeout: 2s

    networks:
      - database

    ports:
      - 127.0.0.1:10026:3306

    restart: unless-stopped

    volumes:
      - db:/var/lib/mysql
      - ./fs/etc/mysql/conf.d:/etc/mysql/conf.d


  mailtrap:
    image: dbck/mailtrap

    environment:
      MAILTRAP_ROUNDCUBE_NAME: Mailtrap Woo

    networks:
      - mail


  wordpress:
    build:
      args:
        - DOCKER_PROXY
        - PHP_VERSION
        - WORDPRESS_VERSION
      context: .
      dockerfile: ./Dockerfile

    depends_on:
      database:
        condition: service_healthy

    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress

    networks:
      - app
      - database
      - mail

    restart: unless-stopped

    volumes:
      - root-path:/var/www/html
      - ..:/var/www/html/wp-content/plugins/stancer:cached


networks:
  app:
    name: woocommerce-network-app
  database:
    name: woocommerce-network-database
  mail:
    name: woocommerce-network-mail


volumes:
  caddy-config:
  caddy-data:
  db:
  root-path:
